import type { StoreShape } from "@/lib/backend/types";

function isoDaysFromNow(days: number) {
  return new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();
}

function iso(date: string) {
  return new Date(date).toISOString();
}

export function createSeed(): StoreShape {
  return {
    library_items: [
      {
        id: "11111111-1111-4111-8111-111111111001",
        brand: "Northern Afterlight",
        type: "track",
        slug: "glass-latitude",
        title: "Glass Latitude",
        description:
          "A slow-opening cue for frozen harbors and long aerials. Strings sit under a distant pulse.",
        status: "released",
        visibility: "highlight",
        created_at: isoDaysFromNow(-40),
        updated_at: isoDaysFromNow(-2),
        meta: {
          collection: "winter-cycle",
          duration: "2:41",
          catalog_no: "NA-014",
          release_date: isoDaysFromNow(-2),
          mood: ["cinematic", "cold", "wide"],
        },
      },
      {
        id: "11111111-1111-4111-8111-111111111002",
        brand: "Northern Afterlight",
        type: "track",
        slug: "thaw-protocol",
        title: "Thaw Protocol",
        description:
          "Percussive ice-break and low brass. Built for transformation sequences and industrial interiors.",
        status: "released",
        visibility: "public",
        created_at: isoDaysFromNow(-120),
        updated_at: isoDaysFromNow(-90),
        meta: {
          collection: "winter-cycle",
          duration: "3:18",
          catalog_no: "NA-009",
          release_date: isoDaysFromNow(-90),
          mood: ["tension", "mechanical"],
        },
      },
      {
        id: "11111111-1111-4111-8111-111111111003",
        brand: "Northern Afterlight",
        type: "track",
        slug: "night-orchard",
        title: "Night Orchard",
        description:
          "Upcoming cue. Choir fragments over a held cello, written for night exteriors and memory work.",
        status: "scheduled",
        visibility: "highlight",
        created_at: isoDaysFromNow(-10),
        updated_at: isoDaysFromNow(-1),
        meta: {
          collection: "afterlight-vol-ii",
          duration: "4:02",
          catalog_no: "NA-021",
          release_date: isoDaysFromNow(2),
          mood: ["nocturnal", "lyrical"],
        },
      },
      {
        id: "11111111-1111-4111-8111-111111111004",
        brand: "Northern Afterlight",
        type: "project",
        slug: "afterlight-vol-ii",
        title: "Afterlight Vol. II",
        description: "Second volume of the cinematic library. Night cues, harbor air, and long-form drones.",
        status: "active",
        visibility: "public",
        created_at: isoDaysFromNow(-20),
        updated_at: isoDaysFromNow(-1),
        meta: {
          overlay: true,
          year: 2026,
        },
      },
      {
        id: "11111111-1111-4111-8111-111111111005",
        brand: "Northern Afterlight",
        type: "project",
        slug: "signal-film-score",
        title: "Signal — Film Score",
        description: "Score fragments prepared for a northern-set independent film.",
        status: "active",
        visibility: "public",
        created_at: isoDaysFromNow(-200),
        updated_at: isoDaysFromNow(-30),
        meta: {
          overlay: false,
          year: 2025,
        },
      },
      {
        id: "11111111-1111-4111-8111-111111111101",
        brand: "USoD MG",
        type: "lore",
        slug: "the-ugly-side",
        title: "The Ugly Side",
        description: "First lore entry. The governing brand names the fracture and keeps the map.",
        status: "published",
        visibility: "public",
        created_at: iso("2024-11-01T15:00:00-05:00"),
        updated_at: iso("2024-11-01T15:00:00-05:00"),
        meta: {
          curated: true,
          overlay: true,
          chapter: 1,
        },
      },
      {
        id: "11111111-1111-4111-8111-111111111102",
        brand: "USoD MG",
        type: "lore",
        slug: "afterlight-transmission",
        title: "Afterlight Transmission",
        description: "How Northern Afterlight began sending catalog as weather, not product.",
        status: "published",
        visibility: "public",
        created_at: iso("2025-03-12T12:00:00-04:00"),
        updated_at: iso("2025-03-12T12:00:00-04:00"),
        meta: {
          curated: true,
          overlay: true,
          chapter: 2,
        },
      },
      {
        id: "11111111-1111-4111-8111-111111111201",
        brand: "Fourth Brand",
        type: "experiment",
        slug: "sandbox-000",
        title: "Sandbox 000",
        description: "First experimental surface. Routing, components, and opt-in library visibility.",
        status: "active",
        visibility: "experimental",
        created_at: isoDaysFromNow(-14),
        updated_at: isoDaysFromNow(-1),
        meta: {
          overlay: true,
          lab: true,
        },
      },
      {
        id: "11111111-1111-4111-8111-111111111202",
        brand: "Fourth Brand",
        type: "experiment",
        slug: "routing-drift",
        title: "Routing Drift",
        description: "Tests brand-context enforcement on dynamic experiment routes.",
        status: "active",
        visibility: "experimental",
        created_at: isoDaysFromNow(-7),
        updated_at: isoDaysFromNow(-3),
        meta: {
          overlay: true,
          lab: true,
        },
      },
    ],
    library_collections: [
      {
        id: "12121212-1111-4111-8111-111111111001",
        brand: "Northern Afterlight",
        name: "Winter Cycle",
        slug: "winter-cycle",
        description: "Cold-weather cues for landscape, infrastructure, and withheld emotion.",
        created_at: isoDaysFromNow(-130),
        updated_at: isoDaysFromNow(-2),
        meta: { curated: true },
      },
      {
        id: "12121212-1111-4111-8111-111111111002",
        brand: "Northern Afterlight",
        name: "Afterlight Vol. II",
        slug: "afterlight-vol-ii",
        description: "Night catalog currently entering a release window.",
        created_at: isoDaysFromNow(-20),
        updated_at: isoDaysFromNow(-1),
        meta: { curated: true },
      },
    ],
    clients: [
      {
        id: "33333333-3333-4333-8333-333333333001",
        name: "Maya Chen",
        email: "maya@example.com",
        brand: "Fifty-Seven Mastering",
        created_at: isoDaysFromNow(-21),
        updated_at: isoDaysFromNow(-1),
        meta: { city: "Toronto" },
      },
      {
        id: "33333333-3333-4333-8333-333333333002",
        name: "Harbor Records",
        email: "studio@harbor.example",
        brand: "Fifty-Seven Mastering",
        created_at: isoDaysFromNow(-40),
        updated_at: isoDaysFromNow(-2),
        meta: { city: "Halifax" },
      },
      {
        id: "33333333-3333-4333-8333-333333333003",
        name: "Lumen",
        email: "a@lumen.example",
        brand: "Fifty-Seven Mastering",
        created_at: isoDaysFromNow(-3),
        updated_at: isoDaysFromNow(-3),
        meta: { city: "Brooklyn" },
      },
    ],
    jobs: [
      {
        id: "22222222-2222-4222-8222-222222222001",
        brand: "Fifty-Seven Mastering",
        client_id: "33333333-3333-4333-8333-333333333001",
        status: "in_progress",
        rush: true,
        intake_form_data: {
          project_name: "North Window",
          track_count: 4,
          sample_rate: "96kHz",
          bit_depth: "24-bit",
          notes: "Leave the low end heavy. Reference: analog hip-hop masters.",
        },
        delivery_links: {},
        created_at: isoDaysFromNow(-2),
        updated_at: isoDaysFromNow(-1),
        meta: { service_flow: "required" },
      },
      {
        id: "22222222-2222-4222-8222-222222222002",
        brand: "Fifty-Seven Mastering",
        client_id: "33333333-3333-4333-8333-333333333002",
        status: "ready_for_delivery",
        rush: false,
        intake_form_data: {
          project_name: "Harbor EP",
          track_count: 6,
          sample_rate: "48kHz",
          bit_depth: "24-bit",
          notes: "Streaming + vinyl parts.",
        },
        delivery_links: {
          dropbox_folder: "/Fifty-Seven Mastering/Clients/Harbor Records/Harbor EP/Deliverables",
          dropbox_link: "https://www.dropbox.com/scl/fo/mock-harbor-ep",
          samply_project: "FSM-Harbor-Records-Harbor-EP-22222222-2222-4222-8222-222222222002",
          samply_link:
            "https://samply.app/p/FSM-Harbor-Records-Harbor-EP-22222222-2222-4222-8222-222222222002",
        },
        created_at: isoDaysFromNow(-12),
        updated_at: isoDaysFromNow(-1),
        meta: { service_flow: "required" },
      },
      {
        id: "22222222-2222-4222-8222-222222222003",
        brand: "Fifty-Seven Mastering",
        client_id: "33333333-3333-4333-8333-333333333003",
        status: "received",
        rush: false,
        intake_form_data: {
          project_name: "Lumen 01",
          track_count: 1,
          sample_rate: "44.1kHz",
          bit_depth: "24-bit",
          notes: "Single. Tight limiter, no clipping.",
        },
        delivery_links: {},
        created_at: isoDaysFromNow(-3),
        updated_at: isoDaysFromNow(-3),
        meta: { service_flow: "required" },
      },
    ],
    signals: [
      {
        id: "44444444-4444-4444-8444-444444444001",
        brand: "USoD MG",
        type: "timeboxed",
        payload: {
          title: "Transmission 07",
          body: "The catalog is a weather system. Listen on the northern side of the hour.",
        },
        active: true,
        created_at: isoDaysFromNow(-1),
        expires_at: isoDaysFromNow(5),
        meta: { channel: "public" },
      },
      {
        id: "44444444-4444-4444-8444-444444444002",
        brand: "USoD MG",
        type: "timeboxed",
        payload: {
          title: "Archive Pulse",
          body: "Expired signal retained for timeline reconstruction.",
        },
        active: false,
        created_at: isoDaysFromNow(-20),
        expires_at: isoDaysFromNow(-10),
        meta: { channel: "archive" },
      },
    ],
    timeline_events: [
      {
        id: "55555555-5555-4555-8555-555555555001",
        brand: "USoD MG",
        title: "Ugly Side of Drama named",
        description: "Parent brand established as the governing identity for the ecosystem.",
        timestamp: iso("2024-09-01T12:00:00-04:00"),
        meta: { layer: "origin" },
      },
      {
        id: "55555555-5555-4555-8555-555555555002",
        brand: "USoD MG",
        title: "USoD Music Group formed",
        description: "Record label introduced. Governance later refers to the same brand as USoD MG.",
        timestamp: iso("2024-11-01T12:00:00-05:00"),
        meta: { layer: "label" },
      },
      {
        id: "55555555-5555-4555-8555-555555555003",
        brand: "USoD MG",
        title: "Northern Afterlight catalog live",
        description: "Cinematic library connected to Supabase.library.",
        timestamp: iso("2025-02-14T12:00:00-05:00"),
        meta: { layer: "library" },
      },
      {
        id: "55555555-5555-4555-8555-555555555004",
        brand: "USoD MG",
        title: "Fifty-Seven desks online",
        description: "Mastering intake, status, and delivery routes opened.",
        timestamp: iso("2025-06-21T12:00:00-04:00"),
        meta: { layer: "service" },
      },
    ],
    automation_triggers: [
      {
        id: "66666666-6666-4666-8666-666666666001",
        source: "supabase.mastering_jobs.jobs",
        event_type: "job_created",
        payload: {
          job_id: "22222222-2222-4222-8222-222222222003",
          brand: "Fifty-Seven Mastering",
        },
        created_at: isoDaysFromNow(-3),
        meta: { scenario: "mastering_intake_confirmation" },
      },
    ],
    pages: [
      {
        slug: "home",
        title: "Ugly Side of Drama",
        brand: "Ugly Side of Drama",
        layout: "parent_home",
        content_blocks: {
          kicker: "Parent brand",
          headline: "One governing identity for every brand that follows.",
          body: "Ugly Side of Drama holds routing, identity, and governance for the ecosystem.",
        },
        seo_meta: { title: "Ugly Side of Drama" },
      },
    ],
    posts: [
      {
        slug: "ice-as-instrument",
        title: "Ice as Instrument",
        brand: "Northern Afterlight",
        body: "Field recordings from the harbor wall, pitched down until the grain became percussion. The library does not decorate the picture. It occupies the same temperature.",
        tags: ["journal", "process"],
        published_at: isoDaysFromNow(-12),
        seo_meta: { title: "Ice as Instrument — Northern Afterlight" },
      },
      {
        slug: "cue-lengths",
        title: "Cue Lengths That Survive the Cut",
        brand: "Northern Afterlight",
        body: "Most picture editors steal the middle. We write heads and tails that still resolve when the middle is gone.",
        tags: ["journal", "sync"],
        published_at: isoDaysFromNow(-40),
        seo_meta: { title: "Cue Lengths That Survive the Cut" },
      },
    ],
    brand_pages: [
      {
        brand: "Northern Afterlight",
        slug: "home",
        title: "Northern Afterlight",
        hero_block: {
          kicker: "Cinematic library",
          headline: "Music for cold light and long cuts.",
        },
        sections: [
          { key: "library", title: "Library" },
          { key: "projects", title: "Projects" },
        ],
      },
      {
        brand: "Fifty-Seven Mastering",
        slug: "home",
        title: "Fifty-Seven Mastering",
        hero_block: {
          kicker: "Studio",
          headline: "Mastering with a named queue, not a black box.",
        },
        sections: [
          { key: "intake", title: "Intake" },
          { key: "delivery", title: "Delivery" },
        ],
      },
      {
        brand: "USoD MG",
        slug: "home",
        title: "USoD MG",
        hero_block: {
          kicker: "USoD Music Group",
          headline: "Signals, lore, and the label's public timeline.",
        },
        sections: [
          { key: "signals", title: "Signals" },
          { key: "timeline", title: "Timeline" },
        ],
      },
      {
        brand: "Fourth Brand",
        slug: "home",
        title: "Fourth Brand",
        hero_block: {
          kicker: "Auxiliary",
          headline: "A sandbox with the same governance as everyone else.",
        },
        sections: [
          { key: "experiments", title: "Experiments" },
          { key: "lab", title: "Lab" },
        ],
      },
    ],
    static_content_blocks: [
      {
        key: "parent_about",
        brand: "Ugly Side of Drama",
        content:
          "Ugly Side of Drama is the parent brand. It does not deliver files and it does not run a service queue. It names the other brands, holds the routing shell, and keeps governance in one place.",
        meta: { page: "about" },
      },
      {
        key: "fsm_faq_turnaround",
        brand: "Fifty-Seven Mastering",
        content:
          "Standard turnaround is five working days. Rush jobs are flagged, prioritized in the queue, and receive additional status emails while in progress.",
        meta: { page: "faq" },
      },
      {
        key: "na_sync_note",
        brand: "Northern Afterlight",
        content:
          "Sync inquiries are answered from the same catalog the public library uses. Highlights are time-bound to each release window.",
        meta: { page: "about" },
      },
    ],
    email_log: [],
  };
}
